### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by covex-nn**
## Changelog

```markdown
### Added
- Added composer.json
```

## Subject

`composer.json` contains three dependencies: `sonata-project/media-bundle`, `sonata-project/doctrine-mongodb-admin-bundle` and `alcaeus/mongo-php-adapter`.

### CODE REVIEW

**Review by kunicmarko20 — APPROVED** [review]

**Comment by covex-nn** [comment]
@kunicmarko20 how do you think, can i merge it? =)

**Comment by kunicmarko20** [comment]
Done 😄

**Comment by covex-nn** [comment]
Thank you, @kunicmarko20 (c) :smile:

**Comment by kunicmarko20** [comment]
Thank you!

**Pull request merged**
